### ISSUE TITLE
Initialization Error

### ISSUE THREAD

**Issue by MwC-Trexx** [hassio-addons/addon-docker-enabler#3]
# Problem/Motivation

See errors during ADD-ON startup

`[cont-init.d] 00-banner.sh: executing... 
-----------------------------------------------------------
 Hass.io Add-on: Docker Enabler v0.3.0
 Grants an add-on access to the Docker socket
parse error: Expected string key before ':' at line 1, column 4
[11:25:47-0500] ERROR ----> Unknown HTTP error occured
 From: 
parse error: Expected string key before ':' at line 1, column 4
[11:25:49-0500] ERROR ----> Unknown HTTP error occured
 By: 
-----------------------------------------------------------
 armhf / HassOS 1.11 / HA 0.79.3 / SU 133 / stable`

## Steps to reproduce

Startup of add-on with default settings

**Comment by adipose** [comment]
I have the same issue.

**Comment by frenck** [comment]
Due to recent changes to Hassio, the add-on can no longer be used.
It has been removed from the add-on store.
